### ISSUE TITLE
Page title does not change when route changes

### ISSUE THREAD

**Issue by POleszkiewicz** [Metnew/vue-element-starter#4] opened 2017-04-19 19:04 UTC
instead of setting the pageTitle in data()

it should be :

computed: {
pageTitle: function () {return this.$route && this.$route.meta && this.$route.meta.title || 'Title' }
}

then it works correctly

**Comment by Metnew** [comment] 2017-04-22 22:39
Thanks for your issue, it will be fixed soon + dependencies will be updated and some code will be updated too 😉

**Comment by Metnew** [comment] 2017-04-29 22:41
Sorry for a big delay, the issue is fixed, also added many new features: UI actions relies on Vuex, minified bundle, some cool webpack plugins, and etc.

**Closed by Metnew** 2017-04-29 22:41 UTC

**Comment by POleszkiewicz** [comment] 2017-04-29 22:43
Thanks :)

**Comment by POleszkiewicz** [comment] 2017-04-29 22:45
btw Are there any breaking changes / is there a possibility for an easy/painless upgrade ?

**Comment by Metnew** [comment] 2017-04-29 22:53
yes, of course, also, starter now is supporting only `.scss`/`.css` styles extension, loaders for other preprocessor have been excluded.
Just try to replace your `/build` folder with new `/build` folder, if you want better webpack build.

**Comment by Metnew** [comment] 2017-04-29 22:57
I'm not sure that I will maintain this repo for a long time :( 
Better Webpack configuration + code organization you can find [in this repo](https://github.com/Metnew/react-semantic.ui-starter), sorry, it's written in React.

**Comment by POleszkiewicz** [comment] 2017-04-29 22:59
I guess I'll stay with Vue :) ,Thanks :)

**Comment by Metnew** [comment] 2017-04-29 23:00
If you want to upgrade Vue stuff - just add `client/store/ui` and upgrade Sidebar, Header + upgrade App code that is responsible for UI actions (openSidebar, closeSidebar)

**Comment by Metnew** [comment] 2017-04-29 23:00
React is better, hah :)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:07
Actually what I am looking for is maximum simplicity :) (ok, not PHP-ish simplicity) :P

**Comment by Metnew** [comment] 2017-04-29 23:11
Oh, maybe old good known AngularJS 1.5 is a killer solution for your task :)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:12
still Vue seems just simpler :)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:14
Another thing is there is no "real" task, mostly brushing up on some skills to be able to prototype fast (in daily life I'm a CEO, this is just something extra :)

**Comment by Metnew** [comment] 2017-04-29 23:14
Vue is a "child" of Angular, also. Directives like `v-model`, `v-click` are very close to Angular's `ng-model`, `ng-click`

**Comment by Metnew** [comment] 2017-04-29 23:16
Then Vue maybe is the best solution, really. Daily life, hah)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:17
Actually we are just 1 hour apart now :)

**Comment by Metnew** [comment] 2017-04-29 23:18
Where are you from?

**Comment by POleszkiewicz** [comment] 2017-04-29 23:18
Poland

**Comment by Metnew** [comment] 2017-04-29 23:20
Oh, I hope I visit Poland after 12.06.2016, if you know what I'm talking about :)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:21
end of visas ? ;-)

**Comment by Metnew** [comment] 2017-04-29 23:22
Sorry, offtop question absolutely not about code: Do people in EU really like this decision? To end visas with Ukraine

**Comment by POleszkiewicz** [comment] 2017-04-29 23:24
A good thing if you ask me, but probably there are some that are not happy with it. Officially this will be only tourist/business purposes with no work permit, but you know how this works :P

**Comment by Metnew** [comment] 2017-04-29 23:29
Personally, I want to see results of this decision and I guess these results will not be so successful. 
I hope I can just hide in EU from Ukrainian conscription :)

**Comment by POleszkiewicz** [comment] 2017-04-29 23:44
Yup, this (war) is really crazy, and then we call ourselves civilized people.

**Comment by Metnew** [comment] 2017-04-29 23:51
But not so crazy as programming Facebook's frontend in x64 assembly :)

**Comment by POleszkiewicz** [comment] 2017-04-30 00:13
haha, true
