### ISSUE TITLE
Linter warnings for element-variables.css

### ISSUE THREAD

**Issue by davestewart** [Metnew/vue-element-starter#9] opened 2017-06-14 09:55 UTC
`npm run lint` is failing on the first line of `client/element-variables.css`:

```
/Users/davestewart/Sites/dev/vue-element/client/element-variables.css
  1:1  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```

I presume that this is because ESLint lints only JS, though it seems to be ignoring the SCSS files OK.

A quick google suggests adding an `.eslintignore` file (can also use `--ignorepath`).

This solves the error, but I get a warning:

```
/Users/davestewart/Sites/dev/vue-element/client/element-variables.css
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```
So I've tried `--quiet` and that works, but I have a few questions:

1. Is this the right way to solve this?
2. How come SCSS files seem to get ignored?
3. Yet, if I create a S/CSS file that I created in the root, it fails as well

I suppose my question really is, is the linting for this project working as-designed, or does it need more work?

Thanks Vlad

**Comment by Metnew** [comment] 2017-06-14 11:21
Hi, thanks for your issue and participating in project :)
I didn't see this warning before, maybe it was caused by the latest dependency ~or I just didn't pay attention.~
It was fixed in beac52d4d3cb950a7ae8be5c6d5baa1c66355702. Just move `element-variables.css` into `client/styles` folder.

**Comment by davestewart** [comment] 2017-06-14 11:37
Hey, that's great :)

Can you explain why these errors occur?

I obviously don't understand how the linter command is doing its thing.

**Comment by Metnew** [comment] 2017-06-14 13:20
As I understand, at first linter checks all(!) files in folder even if some of them have disallowed extensions (in this case it was `.css`). Then linter checks all dirs with files recursively, but only with `*.js, *.vue` extensions. But I'm not sure about it :)

**Closed** 2017-06-15 11:08 UTC
